version: '2'
services:

# HOME ASSISTANT
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    ports:
      - "8123:8123/tcp"
    network_mode: host
    volumes:
      - './home_assistant/config/:/config/'
    environment:
      - TZ=Europe/Warsaw
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    depends_on:
      - mqtt
      - zigbee2mqtt
      - duckdns
      # - swag

# MQTT
  mqtt:
    container_name: mqtt
    restart: always
    image: eclipse-mosquitto
    user: "1000:1000"
    privileged: true
    # network_mode: host
    volumes:
      - ./mqtt:/mosquitto
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "1883:1883"
      - "9001:9001"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"

# ZIGBEE2MQTT

  zigbee2mqtt: # https://www.zigbee2mqtt.io/information/docker.html
    container_name: zigbee2mqtt
    image:  koenkk/zigbee2mqtt:latest #1.6.0
    restart: always
    # network_mode: host
    privileged: true
    volumes:
      - ./zigbee2mqtt/data:/app/data
    environment:
      - TZ=Europe/Warsaw    
    devices:
      - /dev/ttyS0:/dev/ttyACM0 # to check usb position > ls -ltr /dev/tty*|tail -n 1
    depends_on:
      - mqtt

# DUCKDNS - Dynamic DNS provider
  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=Europe/Warsaw
      - SUBDOMAINS=<twoja_domena>         # WPISZ SWOJE DANE
      - TOKEN=<twoj_token>    # WPISZ SWOJE DANE
      - LOG_FILE=true #optional
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    restart: always

# # SWAG - reverse proxy + certification
#   swag:
#     image: linuxserver/swag
#     container_name: swag
#     cap_add:
#       - NET_ADMIN
#     environment:
#       - PUID=1000
#       - PGID=1000
#       - TZ=Europe/Warsaw
#       - URL=<twoja_domena>
#       - SUBDOMAINS=wildcard
#       - VALIDATION=duckdns
#       - DUCKDNSTOKEN=<twoj_token>
#     network_mode: host
#     volumes:
#       - ./swag/config:/config
#     ports:
#       - 443:443
#     logging:
#       driver: "json-file"
#       options:
#         max-size: "1m"
#         max-file: "10"
#     restart: always
